### ISSUE TITLE
Download Files task is using 1.1 api but 2.0 api is the default

### ISSUE THREAD

**Issue by jeamland** [RackHD/on-tasks#351]
`on-tasks/lib/tasks/download-files.js` has the following:

```
        fileMd5Uri: '{{ api.files }}/md5/{{ options.file }}/latest',
        fileUri: '{{ api.files }}/{{ options.file }}/latest',
```

which match up with the 1.1 api but not the now-default 2.0 api.

**Comment by amymullins** [comment]
FYI @brianparry , @BillyAbildgaard , @geoff-reid , @dalebremner , and @srinia6 

New story in the backlog: https://www.pivotaltracker.com/story/show/131562837

**Comment by zyoung51** [comment]
Also, the 1.1 API returns the md5 as a quoted string, but the 2.0 returns it unquoted.  An unquoted string causes the 'test' command to fail when comparing to the quoted string:
```
curl http://localhost:8080/api/1.1/files/md5/file2.img/latest
"91ca69c347766ab1f601af14d770b7f3"
vs.
curl http://localhost:8080/api/current/files/file2.img/md5
91ca69c347766ab1f601af14d770b7f3
```

**Comment by amymullins** [comment]
All three PRs have been merged to resolve this github issue
