### ISSUE TITLE
can't create ipmi obm settings from rmm catalog

### ISSUE THREAD

**Issue by ytjohn** [RackHD/on-tasks#395]
Background: We have EMC ECS hardware. The OBM that rackhd needs to control is in the rmm catalog (ipmi channel 3).  Discovery has no problem generating the bmc and rmm catalogs, but when we attempt to run a workflow that create obm ipmi settings, it fails. We end up with no obm settings available.

```
# curl -s http://localhost:8080/api/1.1/nodes/588914caf5fef0a55f1db847/obm |python -mjson.tool
[]
```

we created a workflow
```
{
    "friendlyName": "ECS Create IPMI",
    "injectableName": "Graph.Rubicon.ECS.IPMI",
    "options": {
        "create-ipmi-obm-settings": {
            "ipmichannel": 3,
            "password": "password",
            "user": "root"
        }
    },
    "tasks": [
        {
            "label": "bootstrap-ubuntu",
            "taskName": "Task.Linux.Bootstrap.Ubuntu"
        },
        {
            "label": "create-ipmi-obm-settings",
            "taskName": "Task.Obm.Ipmi.CreateSettings"
        }
    ]
}
```

We run the workflow, and when it gets to the "create-ipmi-obm-settings" task, it fails with this error:

        "77bd5269-b4a2-49a7-8c9d-bea22680f274": {
            "error": "TypeError: Cannot read property 'data' of undefined\n    at /var/renasar/on-taskgraph/node_modules/on-tasks/lib/jobs/create-ipmi-obm-settings.js:76:49\n    at tryCatcher (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)\n    at Promise._settlePromises (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)\n    at Async._drainQueue (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)",
            "friendlyName": "Create IPMI OBM settings",
            "ignoreFailure": false,
            "implementsTask": "Task.Base.Obm.Ipmi.CreateSettings",
            "injectableName": "Task.Obm.Ipmi.CreateSettings",
            "instanceId": "77bd5269-b4a2-49a7-8c9d-bea22680f274",
            "label": "create-ipmi-obm-settings",
            "name": "Task.Obm.Ipmi.CreateSettings",
            "options": {
                "_taskTimeout": 86400000,
                "ipmichannel": 3,
                "password": "password",
                "user": "root"
            },

If we look at [create-ipmi-obm-settings.js:76](https://github.com/RackHD/on-tasks/blob/master/lib/jobs/create-ipmi-obm-settings.js#L63-L76)

        if (this.options.ipmichannel === '3') {
            catalogSource = 'rmm';
        } else if (this.options.ipmichannel) {
            catalogSource = 'bmc-%s'.format(this.options.ipmichannel);
        } else {
            catalogSource = 'bmc';
        }

        // TODO: Once a BMC can be referenced by mac address in order to get the IP
        // address dynamically via the lookup service, then we won't need to grab
        // the IP from the catalog anymore. Short term solution.
        return waterline.catalogs.findLatestCatalogOfSource(self.nodeId, catalogSource)
        .then(function(catalog) {
            self.obmConfig.config.host = catalog.data['MAC Address'];
            
Both my "rmm" and "bmc" catalog have a data block.

```
  root@rackhd01:# curl --silent http://localhost:8080/api/1.1/nodes/588914caf5fef0a55f1db847/catalogs/bmc |python -mjson.tool
  {
      "createdAt": "2017-01-25T21:13:24.319Z",
      "data": {
          ..snip..
          "MAC Address": "00:1e:67:bc:ed:74",

  root@rackhd01:# curl --silent http://localhost:8080/api/1.1/nodes/588914caf5fef0a55f1db847/catalogs/rmm |python -mjson.tool
  {
      "createdAt": "2017-01-25T21:13:24.347Z",
      "data": {
        ..snip..
        "MAC Address": "00:1e:67:bc:ed:76",          
```

**Comment by manfrednde** [comment]
it looks like host should be defined after line 47 
https://github.com/RackHD/on-tasks/blob/master/lib/jobs/create-ipmi-obm-settings.js#L47

**Comment by ytjohn** [comment]
After working with @manfrednde we believe that the else if is causing `catalogSource = 'rmm';` to never occur. When I get rid of the else if block, it works for me.

```
        if (this.options.ipmichannel === '3') {
            catalogSource = 'rmm';
        } else if (this.options.ipmichannel) {
            catalogSource = 'bmc-%s'.format(this.options.ipmichannel);
```

**Comment by ytjohn** [comment]
After review, this block is expecting ipmichannel to be a string, not an integer. Once I updated my workflow to send a string "3", workflow started working for me.

For those less familiar with javascript comparators (like me), my recommendation is that we put a comment above this block drawing attention to the string requirement.

**Comment by johren** [comment]
Opened https://rackhd.atlassian.net/browse/RAC-4123

**Comment by pscharla** [comment]
Closing this github issue out to continue discussion in the RAC @johren opened.
