### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.  (found in <Root>)

### ISSUE THREAD

**Issue by aimee-2016** [RackHD/on-tasks#417]
vue渲染不到这个页面，webpack是正常的

**Comment by leoyjchang** [comment]
@aimee-2016 , can you please provide detailed information about the issue you found? Thanks.

**Comment by pscharla** [comment]
@leoyjchang @aimee-2016 I created this RAC to replace this github issue:
https://rackhd.atlassian.net/browse/RAC-4723
